<?php
$openinviter_settings=array(
'username'=>"",
'private_key'=>"",
'cookie_path'=>"/tmp",
'transport'=>"curl",
'local_debug'=>"on_error",
'remote_debug'=>"",
'hosted'=>"",
'proxies'=>array(),
'stats'=>"",
'plugins_cache_time'=>"1800",
'plugins_cache_file'=>"oi_plugins.php",
'update_files'=>"0",
'stats_user'=>"",
'stats_password'=>"",
'message_body'=>"",
'message_subject'=>""
);
?>