<!-- 
/**
 * @category   Auguria
 * @package    Auguria_Sponsorship
 * @author     Auguria
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
 -->
<?php 
	$customerId = $this->getUserId();
	$customer = Mage::getModel('customer/customer')->load($customerId);	
	
?>
<?php if (Mage::getStoreConfig('sponsorship/fidelity/fidelity_enabled')):?>
<?php echo $this->__('Fidelity points:') ?> <?php echo floor($customer->getFidelityPoints()); ?>
<br/>
<?php endif;?>