<!-- 
/**
 * @category   Auguria
 * @package    Auguria_Sponsorship
 * @author     Auguria
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
 -->
<?php 
	$customerId = $this->getUserId();
	$customer = Mage::getModel('customer/customer')->load($customerId);	
	$nbSponsor = $this->getNbParrainages ($customerId);	
?>
<?php if (Mage::getStoreConfig('sponsorship/sponsor/sponsor_enabled')):?>
<?php echo $this->__('Sponsorship points:') ?> <?php echo floor($customer->getSponsorPoints()); ?>
<br/>
<?php echo $this->__('Active godsons:') ?> <?php echo $nbSponsor; ?>
<br/>
<a href="<?php echo $this->getUrl('sponsorship_info') ?>"><?php echo $this->__('Principles of Sponsorship')?></a>
<br/>
<a href="<?php echo $this->getUrl('sponsorship') ?>"><?php echo $this->__('Sponsor friends')?></a>
<br/>
<?php endif;?>